<a href="https://colab.research.google.com/github/divineachu05/DevOpsDemos/blob/master/Numpy%20_DataScience_MB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>
    <b>
        NUMPY</b>
    </h>


NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

<b>What is NumPy?</b>

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

It is an open source project and you can use it freely.

<b>Why Use NumPy?</b>

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

<b>Why is NumPy Faster Than Lists?</b>

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

<b>NumPy Getting Started</b>

Installation of NumPy

If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command:

<b>pip install numpy</b>

Import NumPy
Once NumPy is installed, import it in your applications by adding the import keyword:

In [ ]:
import numpy # If you get error as no module found when you are running this code then pip install numpy

Now NumPy is imported and ready to use.

Example:

<b>NumPy as np</b>

NumPy is usually imported under the np alias.

<b>alias:</b> In Python alias are an alternate name for referring to the same thing.

Create an alias with the as keyword while importing:

In [ ]:
import numpy as p #nick name of numpy

Now the NumPy package can be referred to as np instead of numpy.

In [ ]:
arr = p.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
#check version
np.__version__

NameError: name 'np' is not defined

<b>NumPy Creating Arrays</b>

Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [ ]:
arr = np.array([10,20,30])
print(arr)
print(type(arr))

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

Example

Use a tuple to create a NumPy array:

In [ ]:
arr = np.array((1,2,3,4))
arr

In [ ]:
type(arr)

<b>Dimensions in Arrays</b>

A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

<b>0-D Arrays</b>

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

Example

Create a 0-D array with value 42

In [ ]:
arr = np.array(42)
arr

<b>1-D Arrays</b>

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

Example
Create a 1-D array containing the values 1,2,3,4,5:

In [ ]:
arr = np.array([1,2,3])
arr

<b>2-D Arrays</b>

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

Example
Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [ ]:
arr = np.array([[1,2,3],[2,5,6]])
arr

<b>3-D arrays</b>

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.


In [ ]:
arr = np.array([[[1,2,3],[1,4,5]],[[5,6,1],[2,3,6]]])
arr

<b>Check Number of Dimensions?</b>

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

Example
Check how many dimensions the arrays have:

In [ ]:
a = np.array(42)
b = np.array([1,2,3,4,5,6])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[1,4,5]],[[5,6,1],[2,3,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

<b>Higher Dimensional Arrays</b>

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

Example
Create an array with 5 dimensions and verify that it has 5 dimensions:

In [ ]:
arr = np.array([[[1,2,3,4]]],ndmin =2)
print(arr)
print("num of dimensions", arr.ndim)

<h2>NumPy Array Indexing</h2>

<b>Access Array Elements</b>

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

Example

Get the first element from the following array:

In [ ]:
arr = np.array([1,2,3,4])
print(arr[1])

Example

Get third and fourth elements from the following array and add them.

In [ ]:
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

<b>Access 2-D Arrays</b>

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Example

Access the 2nd element on 1st dim:

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('second element on 1st dim is:',arr[1,3])

<b>Access 3-D Arrays</b>

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

Example
Access the third element of the second array of the first array:

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

In [ ]:
[1,2,3]--1D
[[1,2,3],[4,5,6]] ---2D
[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]] --3D

<b>Negative Indexing</b>

Use negative indexing to access an array from the end.

Example

Print the last element from the 2nd dim:

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,-5])

<h1>NumPy Array Slicing</h1>

<b>Slicing arrays</b>

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Example
Slice elements from index 1 to index 5 from the following array:

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[0:])

[1 2 3 4 5 6 7]


Example

Slice elements from index 4 to the end of the array:

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[0:8])

[1 2 3 4 5 6 7]


<b>Negative Slicing</b>

Use the minus operator to refer to an index from the end:

Example

Slice from the index 3 from the end to index 1 from the end:

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-7:-3])

[1 2 3 4]


<b>STEP</b>

Use the step value to determine the step of the slicing:

Example

Return every other element from index 1 to index 5:

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0:8:2])

Example

Return every other element from the entire array:

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[::2])

Slicing 2-D Arrays

Example

From the second element, slice elements from index 1 to index 4 (not included):

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

Example

From both elements, return index 2:

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1,3])

Example

From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[:,1:5])

In [ ]:
arr=np.array([ [1,2,3,4,5], [6,7,8,9,10] ] )
lst=[[1,2,3,4,5], [6,7,8,9,10] ]


print(arr.shape)

<h2>NumPy Data Types</h2>

Data Types in Python

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j
    
Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

Checking the Data Type of an Array

The NumPy array object has a property called dtype that returns the data type of the array:

Example
    
Get the data type of an array object:

In [ ]:
arr = np.array([1,2,3])
print(arr.dtype)
print(type(arr))

<b>NumPy Array Copy vs View</b>

The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

<b>COPY:</b>
    
Example

Make a copy, change the original array, and display both arrays:

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[1] = 50
print(arr)
print(x)

<b>VIEW:</b>
    
Example

Make a view, change the original array, and display both arrays:

The view SHOULD be affected by the changes made to the original array.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[1] = 50
print(arr)
print(x)

Make Changes in the VIEW:

Example

Make a view, change the view, and display both arrays:

The original array SHOULD be affected by the changes made to the view.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
x[1] = 50
print(arr)
print(x)

<h2>NumPy Array Shape</h2>

<b>Shape of an Array</b>

The shape of an array is the number of elements in each dimension.

<b>Get the Shape of an Array</b>

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

<b>Example</b>

Print the shape of a 2-D array:

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
arr.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

<b>NumPy Array Reshaping</b>

<b>Reshaping arrays</b>

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

Reshape From 1-D to 2-D

Example

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(6,2)
print(new_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


<b>Reshape From 1-D to 3-D</b>

Example

Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
#This is for unknown dimension
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,-1)
newarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<b>Iterating Arrays Using nditer()</b>

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

Example
Iterate through the following 3-D array:

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
      print(j)

1
2
3
4
5
6


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
          print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


<b>Iterating With Different Step Size</b>

We can use filtering and followed by iteration.

Example
Iterate through every scalar element of the 2D array skipping 1 element:

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[0:,::2]):
    print(x)

1
3
5
7


<b>Enumerated Iteration Using ndenumerate()</b>

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

Example
Enumerate on following 1D arrays elements:

In [ ]:
arr = np.array([1,2,3])
for a,i in np.ndenumerate(arr):
    print(a,i)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for a,b in np.ndenumerate(arr):
    print(a,b)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


<b>NumPy Joining Array</b>
Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


Example
Join two 2-D arrays along rows (axis=1):

In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis =1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

<b>NumPy Splitting Array</b>

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

Example

Split the array in 3 parts:

In [ ]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

<b>Split Into Arrays</b>

The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

Example
Access the splitted arrays:

In [ ]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


<b>Searching Arrays</b>

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

Example
Find the indexes where the value is 4:

In [ ]:
arr = np.array([1,2,3,4,5,6,7,4,2,4])
x = np.where(arr == 2)
x

(array([1, 8], dtype=int64),)

Example
Find the indexes where the values are even:

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = np.where(arr%2 == 0)
x

(array([1, 3, 5, 7, 9], dtype=int64),)

<b>Search Sorted</b>

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

Example
Find the indexes where the value 7 should be inserted:

In [ ]:
arr = np.array([5,6,7,9,10])
a = np.searchsorted(arr,8)
a

3

<b>Search From the Right Side</b>

By default the left most index is returned, but we can give side='right' to return the right most index instead.

Example
Find the indexes where the value 7 should be inserted, starting from the right:

In [ ]:
arr = np.array([6,7,9,12,15])
a = np.searchsorted(arr,10,side = 'right')
a

3

<b>Multiple Values</b>

To search for more than one value, use an array with the specified values.

Example
Find the indexes where the values 2, 4, and 6 should be inserted:

In [ ]:
arr = np.array([1,3,5,7])
x = np.searchsorted(arr,[2,4,6])
x

array([1, 2, 3], dtype=int64)

<b>Sorting Arrays</b>

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

Example
Sort the array:

In [ ]:
arr = np.array([5,8,7,1,0])
np.sort(arr)

array([0, 1, 5, 7, 8])

<b>Sorting a 2-D Array</b>

If you use the sort() method on a 2-D array, both arrays will be sorted:

Example
Sort a 2-D array:

In [ ]:
arr = np.array([[5,1,0],[9,6,2]])
np.sort(arr)

array([[0, 1, 5],
       [2, 6, 9]])

<b>Random Numbers in NumPy</b>

What is a Random Number?

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Pseudo Random and True Random.

Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Generate Random Number
NumPy offers the random module to work with random numbers.

Example
Generate a random integer from 0 to 100:

In [ ]:
from numpy import random
x = random.randint(100)
x

82

<b>Generate Random Float</b>

The random module's rand() method returns a random float between 0 and 1.

Example
Generate a random float from 0 to 1:

In [ ]:
from numpy import random
x = random.rand()
x

0.3979976452105459

<b>Generate Random Array</b>

In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

Integers

The randint() method takes a size parameter where you can specify the shape of an array.

Example
Generate a 1-D array containing 5 random integers from 0 to 100:

In [ ]:
x = random.randint(100,size =5)
x

array([93, 94, 72, 37, 62])

In [ ]:
x = random.randint(100,size =(3,5,2))
x

array([[[70,  0],
        [49, 22],
        [66, 53],
        [22, 93],
        [26, 41]],

       [[26, 85],
        [76, 43],
        [13, 41],
        [42, 64],
        [65, 33]],

       [[77, 81],
        [37, 27],
        [68, 48],
        [49, 89],
        [98, 37]]])

<b>Generate Random Number From Array</b>

The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

Example
Return one of the values in an array:

The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.

In [ ]:
x=random.choice([3,5,9,10])
x

10